#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Loader for NPZ files generated by precompute_ik_hint.py."""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional, Sequence, Tuple

import numpy as np


@dataclass
class IKHintCache:
    source_path: str
    region_ids: Tuple[str, ...]
    part_ids: Tuple[str, ...]
    scores: np.ndarray
    geometry_valid: np.ndarray
    computed_mask: np.ndarray
    pose_mask: np.ndarray
    grid_height: int
    grid_width: int
    resolution: float

    @classmethod
    def load(
        cls,
        path: str,
        *,
        decision_parts: Optional[Sequence[str]] = None,
        max_poses: Optional[int] = None,
        grid_shape: Optional[Tuple[int, int]] = None,
    ) -> "IKHintCache":
        source = str(Path(path).resolve())
        data = np.load(source, allow_pickle=False)
        required = {
            "region_ids",
            "part_ids",
            "scores",
            "geometry_valid",
            "computed_mask",
            "pose_mask",
            "grid_height",
            "grid_width",
            "resolution",
        }
        missing = sorted(required.difference(data.files))
        if missing:
            raise ValueError(f"IK hint cache missing arrays: {missing}")

        region_ids = tuple(str(x) for x in data["region_ids"].tolist())
        part_ids = tuple(str(x) for x in data["part_ids"].tolist())
        scores = np.asarray(data["scores"], dtype=np.float32)
        geometry_valid = np.asarray(data["geometry_valid"], dtype=bool)
        computed_mask = np.asarray(data["computed_mask"], dtype=bool)
        pose_mask = np.asarray(data["pose_mask"], dtype=bool)
        height = int(np.asarray(data["grid_height"]).item())
        width = int(np.asarray(data["grid_width"]).item())
        resolution = float(np.asarray(data["resolution"]).item())

        if scores.ndim != 5:
            raise ValueError(
                "IK hint scores must have shape [regions,parts,poses,height,width], "
                f"got {scores.shape}"
            )
        expected = (len(region_ids), len(part_ids), scores.shape[2], height, width)
        if scores.shape != expected:
            raise ValueError(f"IK hint score shape mismatch: {scores.shape} != {expected}")
        for name, array in (
            ("geometry_valid", geometry_valid),
            ("computed_mask", computed_mask),
        ):
            if array.shape != scores.shape:
                raise ValueError(f"{name} shape {array.shape} != scores {scores.shape}")
        if pose_mask.shape != (len(part_ids), scores.shape[2]):
            raise ValueError(
                f"pose_mask shape {pose_mask.shape} incompatible with scores {scores.shape}"
            )

        if decision_parts is not None:
            expected_parts = tuple(str(x) for x in decision_parts)
            if expected_parts != part_ids:
                raise ValueError(
                    "IK hint decision part order mismatch: "
                    f"cache={part_ids}, environment={expected_parts}"
                )
        if max_poses is not None and int(max_poses) != scores.shape[2]:
            raise ValueError(
                f"IK hint max_poses={scores.shape[2]} != environment={max_poses}"
            )
        if grid_shape is not None and tuple(grid_shape) != (height, width):
            raise ValueError(
                f"IK hint grid={(height, width)} != environment={tuple(grid_shape)}"
            )

        return cls(
            source_path=source,
            region_ids=region_ids,
            part_ids=part_ids,
            scores=np.clip(scores, 0.0, 1.0),
            geometry_valid=geometry_valid,
            computed_mask=computed_mask,
            pose_mask=pose_mask,
            grid_height=height,
            grid_width=width,
            resolution=resolution,
        )

    @property
    def max_poses(self) -> int:
        return int(self.scores.shape[2])

    def has_region(self, region_id: str) -> bool:
        return str(region_id) in self.region_ids

    def has_part(self, part_id: str) -> bool:
        return str(part_id) in self.part_ids

    def _indices(self, region_id: str, part_id: str) -> Tuple[int, int]:
        try:
            region_index = self.region_ids.index(str(region_id))
        except ValueError as exc:
            raise KeyError(
                f"region {region_id!r} not present in IK cache; regions={self.region_ids}"
            ) from exc
        try:
            part_index = self.part_ids.index(str(part_id))
        except ValueError as exc:
            raise KeyError(
                f"part {part_id!r} not present in IK cache; parts={self.part_ids}"
            ) from exc
        return region_index, part_index

    def map(self, region_id: str, part_id: str) -> np.ndarray:
        region_index, part_index = self._indices(region_id, part_id)
        return self.scores[region_index, part_index].copy()

    def computed(self, region_id: str, part_id: str) -> np.ndarray:
        region_index, part_index = self._indices(region_id, part_id)
        return self.computed_mask[region_index, part_index].copy()

    def value(
        self,
        region_id: str,
        part_id: str,
        pose_id: int,
        row: int,
        col: int,
    ) -> float:
        region_index, part_index = self._indices(region_id, part_id)
        if not (0 <= pose_id < self.max_poses):
            return 0.0
        if not (0 <= row < self.grid_height and 0 <= col < self.grid_width):
            return 0.0
        return float(self.scores[region_index, part_index, pose_id, row, col])

    def positive_action_mask(
        self,
        region_id: str,
        part_id: str,
        *,
        threshold: float = 0.0,
    ) -> np.ndarray:
        values = self.map(region_id, part_id)
        computed = self.computed(region_id, part_id)
        return computed & (values > float(threshold))

    def compact_description(self) -> Dict[str, object]:
        return {
            "source_path": self.source_path,
            "region_ids": list(self.region_ids),
            "part_ids": list(self.part_ids),
            "shape": list(self.scores.shape),
            "grid_shape": [self.grid_height, self.grid_width],
            "resolution": self.resolution,
            "positive_cells": int(np.count_nonzero(self.scores > 0.0)),
            "computed_cells": int(np.count_nonzero(self.computed_mask)),
        }
